# Generated by Django 4.2 on 2023-04-06 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardentry',
            options={'ordering': ['-score', 'timestamp']},
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='player_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='score',
            field=models.PositiveIntegerField(),
        ),
    ]
